INSERT INTO `npieamap` VALUES (0, NULL, 'PROD', 'PROD');
INSERT INTO `npieamap` VALUES (1, NULL, 'Device Information', 'Customer 	\r\nCustomer 	\r\nCustomer ');
INSERT INTO `npieamap` VALUES (2, NULL, 'Device Information', 'Device ');
INSERT INTO `npieamap` VALUES (3, NULL, 'Device Information', 'Die size(mm*mm)');
INSERT INTO `npieamap` VALUES (4, NULL, 'Device Information', 'C/P probe card type');
INSERT INTO `npieamap` VALUES (5, NULL, 'Device Information', 'Probing on bump pad (Y/N)');
INSERT INTO `npieamap` VALUES (6, NULL, 'Wafer Information', 'Wafer Fab');
INSERT INTO `npieamap` VALUES (7, NULL, 'Wafer Information', 'Wafer tech.(nm)');
INSERT INTO `npieamap` VALUES (8, NULL, 'Wafer Information', 'Low K Type');
INSERT INTO `npieamap` VALUES (9, NULL, 'Wafer Information', 'Final Metal Pad type');
INSERT INTO `npieamap` VALUES (10, NULL, 'Wafer Information', 'RV hole(Y/N)');
INSERT INTO `npieamap` VALUES (11, NULL, 'Wafer Information', 'Wafer PSV type / Thickness');
INSERT INTO `npieamap` VALUES (12, NULL, 'Wafer Information', 'Seal-Ring Protected by SiN (Y/N)');
INSERT INTO `npieamap` VALUES (13, NULL, 'Bump structure', 'PKG Type');
INSERT INTO `npieamap` VALUES (14, NULL, 'Bump structure', 'PI type');
INSERT INTO `npieamap` VALUES (15, NULL, 'Bump structure', 'PI Thickness (um)');
INSERT INTO `npieamap` VALUES (16, NULL, 'Bump structure', 'UBM type / Thickness (um)');
INSERT INTO `npieamap` VALUES (17, NULL, 'Bump structure', 'Bump composition');
INSERT INTO `npieamap` VALUES (18, NULL, 'Bump design', 'REPSV PI Opening Size(um)');
INSERT INTO `npieamap` VALUES (19, NULL, 'Bump design', 'Min fianl metal trace to seal ring (um)');
INSERT INTO `npieamap` VALUES (20, NULL, 'Bump design', 'PI via opening bottom edge ');
INSERT INTO `npieamap` VALUES (21, NULL, 'Bump design', 'to pad psv. Edge (um)');
INSERT INTO `npieamap` VALUES (22, NULL, 'Bump design', 'PR thickness(um)');
INSERT INTO `npieamap` VALUES (23, NULL, 'Bump design', 'UBM Size(um)');
INSERT INTO `npieamap` VALUES (24, NULL, 'Bump design', 'UBM Overlap PSV (um)');
INSERT INTO `npieamap` VALUES (25, NULL, 'Bump design', 'UBM insdie final metal for FOC (um)');
INSERT INTO `npieamap` VALUES (26, NULL, 'Bump design', 'UBM Plating Area(dm2)');
INSERT INTO `npieamap` VALUES (27, NULL, 'Bump design', 'UBM Density (UBM Area/Die Area)');
INSERT INTO `npieamap` VALUES (28, NULL, 'Bump design', 'Mushroom CD(um)');
INSERT INTO `npieamap` VALUES (29, NULL, 'Bump design', 'Min Mushroom space(um)');
INSERT INTO `npieamap` VALUES (30, NULL, 'Bump design', 'Min. Bump pitch (um)');
INSERT INTO `npieamap` VALUES (31, NULL, 'Bump design', 'Bump Height(um)');
INSERT INTO `npieamap` VALUES (32, NULL, 'Bump design', 'Bump Diameter(um)');
INSERT INTO `npieamap` VALUES (33, NULL, 'Bump design', 'Bump Density (Bump Q\'ty/Die Area)');
INSERT INTO `npieamap` VALUES (34, NULL, 'Bump design', 'BH/UBM ratio');
INSERT INTO `npieamap` VALUES (35, NULL, 'Outgoing criteria', 'LF Bump Ag% target');
INSERT INTO `npieamap` VALUES (36, NULL, 'Outgoing criteria', 'Bump Height(um)');
INSERT INTO `npieamap` VALUES (37, NULL, 'Outgoing criteria', 'Bump diameter');
INSERT INTO `npieamap` VALUES (38, NULL, 'Outgoing criteria', 'Bump Coplanarity ');
INSERT INTO `npieamap` VALUES (39, NULL, 'Outgoing criteria', 'Bump Shear Strenght');
INSERT INTO `npieamap` VALUES (40, NULL, 'Outgoing criteria', 'Bump void  ');
INSERT INTO `npieamap` VALUES (41, NULL, 'Outgoing criteria', 'PI Rougness (Ra)');
INSERT INTO `npieamap` VALUES (42, NULL, 'Outgoing criteria', 'Bump Resistance (POR capability)');
INSERT INTO `npieamap` VALUES (43, NULL, 'Metrology tool', 'August - Gross die');
INSERT INTO `npieamap` VALUES (44, NULL, 'Metrology tool', 'August - Expose pad');
INSERT INTO `npieamap` VALUES (45, NULL, 'Metrology tool', 'August - PSV1(PI1/PBO1) opening');
INSERT INTO `npieamap` VALUES (46, NULL, 'Metrology tool', 'August - Bump diameter');
INSERT INTO `npieamap` VALUES (47, NULL, 'Metrology tool', 'August - Low SPEC of min RDL Width');
INSERT INTO `npieamap` VALUES (48, NULL, 'Metrology tool', 'August - Low SPEC of min RDL Spacing');
INSERT INTO `npieamap` VALUES (49, NULL, 'Metrology tool', 'August - Min RDL Width/Spacing pattern & location');
INSERT INTO `npieamap` VALUES (50, NULL, 'Metrology tool', 'RVSI - Gross die');
INSERT INTO `npieamap` VALUES (51, NULL, 'Metrology tool', 'RVSI - Bump count per die');
INSERT INTO `npieamap` VALUES (52, NULL, 'Metrology tool', 'RVSI - Bump height');
INSERT INTO `npieamap` VALUES (53, NULL, 'Metrology tool', 'RVSI - Bump diameter');
INSERT INTO `npieamap` VALUES (54, NULL, 'Metrology tool', 'RS meter - Bump diameter');
INSERT INTO `npieamap` VALUES (55, NULL, 'Metrology tool', 'Void (X-ray) - Bump diameter');
INSERT INTO `npieamap` VALUES (56, NULL, 'Metrology tool', 'Bump shear - Bump diameter');
INSERT INTO `npieamap` VALUES (57, NULL, 'Metrology tool', 'Bump pull - Bump diameter');
INSERT INTO `npieamap` VALUES (58, NULL, 'AB requirement', 'Bump to bump space');
INSERT INTO `npieamap` VALUES (59, NULL, 'AB requirement', 'SMO');
INSERT INTO `npieamap` VALUES (60, NULL, 'AB requirement', 'UBM/SMO ratio');
INSERT INTO `npieamap` VALUES (61, NULL, 'Special Requirement', 'Process / Machine');
INSERT INTO `npieamap` VALUES (62, NULL, 'Special Requirement', 'Material');
INSERT INTO `npieamap` VALUES (63, NULL, 'Special Requirement', 'Measurement tool');
INSERT INTO `npieamap` VALUES (64, NULL, 'Special Requirement', 'Reliability');
